### ISSUE TITLE
Metadata support

### ISSUE THREAD

**Issue by trickeydan** [sourcebots/sbot#3]
Blocked on upstream: https://github.com/j5api/j5/issues/165

**Comment by kierdavis** [comment]
As per discussion on j5api/j5#165, this no longer requires functionality from j5 and is therefore ready to be worked on.

The work-in-progress implementation in j5api/j5#313 might be useful.

**Comment by kierdavis** [comment]
As per discussion on j5api/j5#165, this no longer requires functionality from j5 and is therefore ready to be worked on.

The work-in-progress implementation in j5api/j5#313 might be useful.
