### ISSUE TITLE
Decouple reading environment variable from metadata.load

### ISSUE THREAD

**Issue by kierdavis** [sourcebots/sbot#36]
Playing with the environment variables in tests is kinda ugly, and it relies on the assumption that this variable does not already exist in the environment - I think `test_load_no_env_var` will fail if it is set. I'm thinking we should decouple the environment variable interaction from the `load` function to make the latter easier to test.

_Originally posted by @kierdavis in https://github.com/sourcebots/sbot/pull/32/review_comment/create_

**Comment by WillB97** [comment]
Pytest has handling for manipulation the environment switching to this makes the tests reproducible and environment-independent
