### ISSUE TITLE
Support for killing robots at the end of matches

### ISSUE THREAD

**Issue by PeterJCLaw** [sourcebots/sbot#5]
At the end of the match the robots need to stop all movement. This has historically been managed by `robot-api` but is not present in this new API implementation.

**Comment by trickeydan** [comment]
You are correct, this has been overlooked actually.

I suggest taking the `kill_after_delay` function and putting it here. [robot-api implementation](https://github.com/sourcebots/robot-api/blob/master/robot/game.py)

`j5` shouldn't have any game specific things, so I think this is best suited to go here.
