### ISSUE TITLE
Missing support for various constants

### ISSUE THREAD

**Issue by PeterJCLaw** [sourcebots/sbot#6]
Not sure if this is currently expected, however there are various constants from `robot-api` which aren't present here:
- `PowerOutput` (enum)
- `BRAKE` and `COAST`
- `PinMode` and `PinValue` (enums)

And possibly others I've missed.

**Comment by trickeydan** [comment]
This need to be imported from `j5` to make them available to the users.

I knew we needed to do this, but thanks for enumerating it as an issue.

**Comment by trickeydan** [comment]
This has been done #13 and #22
