### ISSUE TITLE
Check thread-safety

### ISSUE THREAD

**Issue by kierdavis** [sourcebots/sbot#61]
It's not unheard of for teams to use threads in their code to do multiple things at once. We should make sure our robot API is thread-safe.

Depends on j5api/j5#381.

**Comment by trickeydan** [comment]
https://github.com/j5api/j5/pull/445

**Comment by trickeydan** [comment]
This has now been merged upstream, so this will require waiting for a release of `j5`

**Comment by trickeydan** [comment]
j5 has now been updated and released. We should write some test code to ensure that it works correctly in multi-threaded scenarios.
