### ISSUE TITLE
Use a less generic name than "metadata.json"

### ISSUE THREAD

**Issue by kierdavis** [sourcebots/sbot#66]
We have observed teams leaving other things on their robot code USB sticks, for example virtualenvs. Some packages installed into a virtualenv also contain a file named "metadata.json". If the sbot metadata search finds one of these files before it finds the one on the arena USB, the wrong file will be loaded (almost certainly not containing "zone" or "is_competition" fields), resulting in bogus MetadataKeyErrors.

We should change the filename to something more specific, e.g. "sbot-metadata.json".

**Comment by tpoomlmly** [comment]
At the moment sbot just checks for any `.json` file

**Comment by trickeydan** [comment]
If you migrate to Astoria, it looks for 
astoria-metadata.json

**Comment by tpoomlmly** [comment]
Good idea; we'll do that instead
