### ISSUE TITLE
Non-main threads are not killed on timeout

### ISSUE THREAD

**Issue by kierdavis** [sourcebots/sbot#69]
When the match timer expires we need to kill all threads, not just the main one.

**Comment by PeterJCLaw** [comment]
Alternatively we should ensure that all the non-main threads are marked as "[daemon threads](https://docs.python.org/3/library/threading.html#thread-objects)". That will mean they get killed for us when all non-daemon threads (i.e: just the main thread for us) exit.

**Comment by trickeydan** [comment]
I'm closing this in favour of https://github.com/sourcebots/runusb/issues/53

The container / process manager should be responsible for ensuring that all threads are killed.
